In [38]:
#Import Languages
import pandas as pd
import numpy as np

In [39]:
#Read excel files
unemp_df = pd.read_excel("../data/raw/laucnty24.xlsx", skiprows=4)
pop_df = pd.read_excel("../data/raw/NST-EST2024-POP.xlsx", skiprows=3)
income_df = pd.read_excel("../data/raw/census_income.xlsx")

In [40]:
unemp_df.columns = unemp_df.columns.astype(str)
pop_df.columns = pop_df.columns.astype(str)
income_df.columns = income_df.columns.astype(str)

In [41]:
#Clean Column names
unemp_df.columns = [col.strip().replace(' ', '_').lower() for col in unemp_df.columns]
pop_df.columns = [col.strip().replace(' ', '_').lower() for col in pop_df.columns]
income_df.columns = [col.strip().replace(' ', '_').lower() for col in income_df.columns]

In [42]:
#Prints the (Rows, Columns) # in each file
print(unemp_df.shape)
print(pop_df.shape)
print(income_df.shape)

(3221, 9)
(64, 7)
(52, 3)

In [43]:
#Prints the names of each column in each list
print(unemp_df.columns.tolist())
print(pop_df.columns.tolist())
print(income_df.columns.tolist())

['cn0100500000000', '01', '005', 'barbour_county,_al', '2024', '8699', '8347', '352', '4']
['unnamed:_0', 'unnamed:_1', '2020', '2021', '2022', '2023', '2024']
['state', 'median_income', 'state.1']

In [44]:
unemp_df.head()

,cn0100500000000,01,005,"barbour_county,_al",2024,8699,8347,352,4
0,CN0100700000000,1.0,7.0,"Bibb County, AL",2024.0,8826.0,8570.0,256.0,2.9
1,CN0100900000000,1.0,9.0,"Blount County, AL",2024.0,26971.0,26281.0,690.0,2.6
2,CN0101100000000,1.0,11.0,"Bullock County, AL",2024.0,4215.0,4060.0,155.0,3.7
3,CN0101300000000,1.0,13.0,"Butler County, AL",2024.0,8060.0,7762.0,298.0,3.7
4,CN0101500000000,1.0,15.0,"Calhoun County, AL",2024.0,49827.0,48288.0,1539.0,3.1

In [45]:
pop_df.head()

,unnamed:_0,unnamed:_1,2020,2021,2022,2023,2024
0,United States,331515736.0,331577720.0,332099760.0,334017321.0,336806231.0,340110988.0
1,Northeast,57617706.0,57431458.0,57252533.0,57159597.0,57398303.0,57832935.0
2,Midwest,68998970.0,68984258.0,68872831.0,68903297.0,69186401.0,69596584.0
3,South,126281537.0,126476549.0,127368010.0,129037849.0,130893358.0,132665693.0
4,West,78617523.0,78685455.0,78606386.0,78916578.0,79328169.0,80015776.0

In [46]:
income_df.head()

        state  median_income  state.1
0     Alabama          66659        1
1      Alaska          95665        2
2     Arizona          81486        4
3    Arkansas          62106        5
4  California         100149        6

In [47]:
#Rename unemployment Columns
unemp_df.columns = ["code", "state_fips", "county_fips", "county_name",
                    "year", "labor_force", "employed", "unemployed", "unemployment_rate"]
unemp_df.head()

,code,state_fips,county_fips,county_name,year,labor_force,employed,unemployed,unemployment_rate
0,CN0100700000000,1.0,7.0,"Bibb County, AL",2024.0,8826.0,8570.0,256.0,2.9
1,CN0100900000000,1.0,9.0,"Blount County, AL",2024.0,26971.0,26281.0,690.0,2.6
2,CN0101100000000,1.0,11.0,"Bullock County, AL",2024.0,4215.0,4060.0,155.0,3.7
3,CN0101300000000,1.0,13.0,"Butler County, AL",2024.0,8060.0,7762.0,298.0,3.7
4,CN0101500000000,1.0,15.0,"Calhoun County, AL",2024.0,49827.0,48288.0,1539.0,3.1

In [48]:
pop_df.columns = ["state", "base_2020", "2020", "2021", "2022", "2023", "2024"]
pop_df.head()

,state,base_2020,2020,2021,2022,2023,2024
0,United States,331515736.0,331577720.0,332099760.0,334017321.0,336806231.0,340110988.0
1,Northeast,57617706.0,57431458.0,57252533.0,57159597.0,57398303.0,57832935.0
2,Midwest,68998970.0,68984258.0,68872831.0,68903297.0,69186401.0,69596584.0
3,South,126281537.0,126476549.0,127368010.0,129037849.0,130893358.0,132665693.0
4,West,78617523.0,78685455.0,78606386.0,78916578.0,79328169.0,80015776.0

In [49]:
income_df = income_df.drop(columns=["state.1"])
income_df.head()

        state  median_income
0     Alabama          66659
1      Alaska          95665
2     Arizona          81486
3    Arkansas          62106
4  California         100149

In [50]:
#Gives me the missing items in each column
print(unemp_df.isnull().sum())
print(pop_df.isnull().sum())
print(income_df.isnull().sum())

code                 1
state_fips           3
county_fips          3
county_name          3
year                 3
labor_force          3
employed             3
unemployed           3
unemployment_rate    3
dtype: int64
state        1
base_2020    7
2020         7
2021         7
2022         7
2023         7
2024         7
dtype: int64
state            0
median_income    0
dtype: int64

In [51]:
#Remove all the unwanted regions and Puerto Rice, and fix names so theres no . at start, also drop all the nulls
pop_df["state"] = pop_df["state"].str.strip().str.replace(".", "", regex=False)
drop_rows = ["United States", "Northeast", "Midwest", "South", "West", "Puerto Rico", None]
pop_df = pop_df[~pop_df["state"].isin(drop_rows)]
pop_df = pop_df[["state", "2024"]].rename(columns={"2024": "population"})
pop_df["population"] = pd.to_numeric(pop_df["population"], errors="coerce")
pop_df = pop_df.dropna()
pop_df.head()

        state  population
5     Alabama   5157699.0
6      Alaska    740133.0
7     Arizona   7582384.0
8    Arkansas   3088354.0
9  California  39431263.0

In [52]:
pop_df.shape

(51, 2)

In [53]:
#filter and keep every row but where the State is Puerto Rico
income_df = income_df[income_df["state"] != "Puerto Rico"]
print(income_df.shape)
income_df.head()

(51, 2)

        state  median_income
0     Alabama          66659
1      Alaska          95665
2     Arizona          81486
3    Arkansas          62106
4  California         100149

In [54]:
#Extract state abbreviation from county Name
unemp_df["state_abbr"] = unemp_df["county_name"].str.extract(r",\s*([A-Z]{2})$")
#Group by state and average unemplyment across all counties
unemp_state = unemp_df.groupby("state_abbr")["unemployment_rate"].mean().reset_index()
unemp_state["unemployment_rate"] = unemp_state["unemployment_rate"].round(2)

print(unemp_state.shape)
unemp_state.head()

(51, 2)

  state_abbr  unemployment_rate
0         AK               5.99
1         AL               3.44
2         AR               4.04
3         AZ               4.94
4         CA               6.14

In [56]:
#Map state abbreviations to full names
state_abbr_map = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "DC": "District of Columbia", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii",
    "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas",
    "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
    "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada",
    "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York",
    "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah",
    "VT": "Vermont", "VA": "Virginia", "WA": "Washington", "WV": "West Virginia",
    "WI": "Wisconsin", "WY": "Wyoming", "DC": "District of Columbia"
    }

unemp_state["state"] = unemp_state["state_abbr"].map(state_abbr_map)
unemp_state = unemp_state.dropna(subset=["state"])

#Merge all three
merged_df = income_df.merge(pop_df, on="state")
merged_df = merged_df.merge(unemp_state[["state", "unemployment_rate"]], on="state")

print(merged_df.shape)
merged_df.head()

(50, 4)

        state  median_income  population  unemployment_rate
0     Alabama          66659   5157699.0               3.44
1      Alaska          95665    740133.0               5.99
2     Arizona          81486   7582384.0               4.94
3    Arkansas          62106   3088354.0               4.04
4  California         100149  39431263.0               6.14

In [57]:
merged_df.to_csv("../data/cleaned/merged_state_data.csv", index=False)
print("Saved to data/cleaned/merged_state_data.csv")

Saved to data/cleaned/merged_state_data.csv